### PR TITLE
Configure maximum number of open files

### PR DESCRIPTION
**Pull request by kramerul**

### CODE REVIEW

**Comment by zachgersh** [comment]
@kramerul what happened that resulted in you needing to raise the file limit?

**Comment by kramerul** [comment]
@zachgersh We did tests with an increasing number of connections with envoy to get an impression, how many memory is used by envoy per connection. The default ulimit (1024) was to low. 
For our scenario, we also expect more than 1000 TCP connections. Therefore, we would like to increase the number of open files.
In our scenario, we are using envoy to tunnel database connections. Java applications are typically using connection pools with a size of a [round about hundred connections](https://stackoverflow.com/questions/1208077/optimal-number-of-connections-in-connection-pool). This means that we would only able to serve 10 application instance with a ulimit fo 1024.

**Comment by ndhanushkodi** [comment]
Hey @kramerul, we think that exposing this property seems alright. We'd like to keep the default at the existing default of 1024 though, any thoughts @kramerul @shubhaat?

**Comment by shubhaat** [comment]
Hello, Given the usecase described above it seems fine to make this property configurable with a default set to `1024` for now.

**Comment by loewenstein** [comment]
@ndhanushkodi defaulting to 1024 sounds good to me. Should we change the PR or do you want to change it while merging?

**Pull request merged**
